/**
 * Extract a gym check-in code from whatever the scanner read.
 *
 * The printed sticker encodes a full URL:
 *
 *     https://yourapp.com/checkin?c=a3f9e1c2b7d84f60
 *
 * ...rather than a bare code, and that is deliberate. In-app scanning is the
 * primary path — it is what gives members a reason to open the app daily — but
 * encoding a URL means someone who scans the same sticker with their phone's
 * built-in camera still lands in the app and still checks in. One sticker,
 * both paths, no extra work.
 *
 * This function therefore has to accept either form.
 */

/**
 * Codes are generated by Postgres as `encode(gen_random_bytes(16), 'hex')`,
 * which is exactly 32 lowercase hex characters. Validating the shape here means
 * a stray QR code on a protein tub is rejected on-device, before it costs a
 * network round trip.
 */
const CODE_RE = /^[0-9a-f]{32}$/i;

export function parseCheckInCode(scanned: string): string | null {
  const raw = scanned.trim();
  if (!raw) return null;

  // Case 1: a bare code.
  if (CODE_RE.test(raw)) return raw.toLowerCase();

  // Case 2: a URL carrying ?c=<code>. Accept any host — the code itself is the
  // credential, and it is validated server-side against gym_qr_codes anyway.
  // Being strict about the host here would only break staging and preview
  // deploys for no security gain.
  try {
    const url = new URL(raw);
    const candidate = url.searchParams.get('c');
    if (candidate && CODE_RE.test(candidate)) return candidate.toLowerCase();
  } catch {
    // Not a URL. Fall through.
  }

  return null;
}
