import React from 'react';
import { Bot, Dumbbell, Utensils } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { DashboardData, DailyPlan } from '../types/dashboard.types';
import { SectionCard, Card, EmptyState, Button, Badge } from '../../../shared';

interface NutritionSectionProps {
  dashboardData: DashboardData | null;
  dailyPlans: DailyPlan[];
  onShowHistory: () => void;
  onUpdatePlan: () => void;
}

export const NutritionSection: React.FC<NutritionSectionProps> = ({
  dashboardData,
  dailyPlans,
  onShowHistory,
  onUpdatePlan
}) => {
  return (
    <SectionCard
      padding="none"
      className="bg-transparent border-none shadow-none"
      title={
        <div className="flex items-center gap-3">
          <div className="p-2 rounded-lg bg-purple-500/10">
            <Bot size={24} className="text-purple-500" />
          </div>
          <div>
            <span className="text-xl font-bold text-text-primary">Workout & Diet Chart</span>
            <p className="text-sm text-text-muted mt-1 font-normal">Your personalized routines generated by STRIVA Coach</p>
          </div>
        </div>
      }
      action={
        <div className="flex gap-2">
          <Button variant="secondary" size="sm" onClick={onShowHistory} className="bg-surface-card hover:bg-surface-elevated border-border-subtle">
            View History
          </Button>
          <Button variant="primary" size="sm" onClick={onUpdatePlan}>
            Update Plan
          </Button>
        </div>
      }
    >
      <div className="space-y-4">
        {dashboardData?.today_plan ? (
          <Card className="p-5 sm:p-6 transition-colors">
            {/* Plan header */}
            <div className="flex justify-between items-start mb-6">
              <div>
                <span className="text-xs font-bold uppercase tracking-widest text-emerald-500">Live Active Plan</span>
                <h4 className="text-2xl font-bold mt-1 text-text-primary">
                  {dashboardData.today_plan.workout_title || 'Daily Routine'}
                </h4>
                <div className="flex gap-2 flex-wrap mt-2">
                  {dashboardData.today_plan.difficulty && (
                    <Badge variant="outline" className="bg-orange-500/10 text-orange-500 border-orange-500/20 uppercase text-[10px]">
                      {dashboardData.today_plan.difficulty}
                    </Badge>
                  )}
                  {dashboardData.today_plan.duration && (
                    <Badge variant="outline" className="bg-blue-500/10 text-blue-500 border-blue-500/20 uppercase text-[10px]">
                      {dashboardData.today_plan.duration}
                    </Badge>
                  )}
                </div>
              </div>
              <div className="text-right">
                 <div className="text-2xl font-bold text-emerald-500">
                    {dashboardData.today_stats?.completed_percentage || 0}%
                 </div>
                 <div className="text-[10px] uppercase font-bold text-zinc-500">Completion</div>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Workout Section */}
              <div className="p-5 rounded-[24px] bg-surface-elevated">
                <div className="flex items-center gap-2 mb-4">
                  <Dumbbell size={18} className="text-emerald-500" />
                  <span className="text-sm font-bold uppercase tracking-widest text-text-primary">Workout Protocol</span>
                </div>
                <div className="space-y-2 max-h-[400px] overflow-y-auto custom-scrollbar pr-1">
                  {dashboardData.today_plan.workout_exercises && dashboardData.today_plan.workout_exercises.length > 0 ? (
                    dashboardData.today_plan.workout_exercises.map((ex: any, idx: number) => (
                      <div key={idx} className="flex items-start gap-3 p-3 rounded-xl bg-black/20 border border-border-subtle">
                        <div className="w-6 h-6 rounded-full bg-emerald-500/10 text-emerald-500 flex items-center justify-center text-[10px] font-bold flex-shrink-0">
                          {idx + 1}
                        </div>
                        <div className="flex-1 min-w-0">
                          <div className="text-sm font-bold text-text-primary">{ex.name}</div>
                          {ex.description && <div className="text-xs mt-0.5 leading-relaxed text-text-secondary">{ex.description}</div>}
                          {(ex.sets || ex.reps) && (
                            <div className="flex gap-2 mt-1.5 flex-wrap">
                              {ex.sets && <Badge variant="outline" className="text-[10px] font-bold text-emerald-500/80 bg-emerald-500/10 border-none">{ex.sets} Sets</Badge>}
                              {ex.reps && <span className="text-[10px] font-bold text-zinc-400">{ex.reps} Reps</span>}
                              {ex.weight && ex.weight !== 'bodyweight' && <span className="text-[10px] font-bold text-zinc-500">@ {ex.weight}</span>}
                            </div>
                          )}
                        </div>
                      </div>
                    ))
                  ) : (
                    <div className="py-6 text-center">
                      <Dumbbell size={28} className="mx-auto mb-2 opacity-20 text-text-muted" />
                      <p className="text-sm italic text-text-muted">Workout plan ready — ask coach for a structured exercise list.</p>
                    </div>
                  )}
                </div>
              </div>

              {/* Diet Section */}
              <div className="p-5 rounded-[24px] bg-surface-elevated">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <Utensils size={18} className="text-orange-500" />
                    <span className="text-sm font-bold uppercase tracking-widest text-text-primary">Meal Schedule</span>
                  </div>
                  {dashboardData.today_plan.calories_target ? (
                    <div className="text-xs font-bold text-orange-500">{dashboardData.today_plan.calories_target} kcal</div>
                  ) : null}
                </div>
                <div className="space-y-3 max-h-[400px] overflow-y-auto custom-scrollbar pr-1">
                  {dashboardData.today_plan.diet_meals && dashboardData.today_plan.diet_meals.length > 0 ? (
                    dashboardData.today_plan.diet_meals.map((meal: any, idx: number) => {
                      const isMarkdownBlob = meal.items?.length === 1 && typeof meal.items[0] === 'string' && meal.items[0].length > 200;
                      return (
                        <div key={idx} className="p-3 rounded-xl bg-black/20 border border-border-subtle">
                          {!isMarkdownBlob && (
                            <div className="flex justify-between items-center mb-1">
                              <div className="text-xs font-bold uppercase tracking-tight text-text-primary">{meal.type || `Meal ${idx+1}`}</div>
                              {meal.calories && <div className="text-[10px] font-bold text-zinc-500">{meal.calories} kcal</div>}
                            </div>
                          )}
                          {isMarkdownBlob ? (
                            <div className="text-xs leading-relaxed prose prose-invert prose-sm max-w-none text-text-secondary">
                              <ReactMarkdown>{meal.items[0]}</ReactMarkdown>
                            </div>
                          ) : (
                            <ul className="text-xs space-y-1 text-text-secondary">
                              {meal.items?.map((item: string, i: number) => (
                                <li key={i} className="flex items-start gap-2"><span className="text-orange-500 flex-shrink-0">•</span><span>{item}</span></li>
                              ))}
                            </ul>
                          )}
                        </div>
                      );
                    })
                  ) : (
                    <div className="py-6 text-center">
                      <Utensils size={28} className="mx-auto mb-2 opacity-20 text-text-muted" />
                      <p className="text-sm italic text-text-muted">
                        {dashboardData.today_plan.diet_title ? `${dashboardData.today_plan.diet_title} ready — ask coach for detailed meals.` : 'No diet plan yet.'}
                      </p>
                    </div>
                  )}
                </div>
                {(dashboardData.today_plan.protein_goal || dashboardData.today_plan.carb_goal || dashboardData.today_plan.fat_goal) ? (
                  <div className="grid grid-cols-3 gap-2 mt-4 pt-4 border-t border-border-subtle">
                    <div className="text-center">
                      <div className="text-xs font-bold text-text-primary">{dashboardData.today_plan.protein_goal}g</div>
                      <div className="text-[9px] uppercase font-bold text-zinc-500">Protein</div>
                    </div>
                    <div className="text-center border-x border-border-subtle">
                      <div className="text-xs font-bold text-text-primary">{dashboardData.today_plan.carb_goal}g</div>
                      <div className="text-[9px] uppercase font-bold text-zinc-500">Carbs</div>
                    </div>
                    <div className="text-center">
                      <div className="text-xs font-bold text-text-primary">{dashboardData.today_plan.fat_goal}g</div>
                      <div className="text-[9px] uppercase font-bold text-zinc-500">Fats</div>
                    </div>
                  </div>
                ) : null}
              </div>
            </div>
          </Card>
        ) : dailyPlans.length > 0 ? (
          dailyPlans.slice(0, 1).map((plan, i) => (
            <Card key={i} className="p-5 sm:p-6">
              <div className="flex justify-between items-start mb-4">
                <h4 className="text-lg font-bold text-text-primary">Daily Routine</h4>
                <span className="text-xs font-bold uppercase tracking-widest text-zinc-500">{plan.date}</span>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="p-4 rounded-2xl bg-surface-elevated/50">
                  <div className="flex items-center gap-2 mb-3">
                    <Dumbbell size={16} className="text-emerald-500" />
                    <span className="text-xs font-bold uppercase text-zinc-400">Workout Plan</span>
                  </div>
                  <div className="text-sm prose prose-invert prose-sm max-w-none text-text-secondary">
                    <ReactMarkdown>{plan.workout_plan}</ReactMarkdown>
                  </div>
                </div>
                <div className="p-4 rounded-2xl bg-surface-elevated/50">
                  <div className="flex items-center gap-2 mb-3">
                    <Utensils size={16} className="text-orange-500" />
                    <span className="text-xs font-bold uppercase text-zinc-400">Diet Plan</span>
                  </div>
                  <div className="text-sm prose prose-invert prose-sm max-w-none text-text-secondary">
                    <ReactMarkdown>{plan.diet_plan}</ReactMarkdown>
                  </div>
                </div>
              </div>
            </Card>
          ))
        ) : (
          <EmptyState
            icon={<Bot size={32} />}
            title="No AI Plan Generated"
            description="Ask STRIVA to generate a personalized workout and diet plan for you."
            className="border-dashed"
          />
        )}
      </div>
    </SectionCard>
  );
};
