-- ==========================================
-- PHASE 4E: INTELLIGENCE & CONTEXT MIGRATION
-- ==========================================

-- 1. AI MEMORY
-- Stores structured long-term memory for the AI.
CREATE TABLE IF NOT EXISTS public.ai_memory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    category TEXT NOT NULL, -- e.g. 'INJURY', 'PREFERENCE', 'GOAL'
    key TEXT NOT NULL,
    value JSONB NOT NULL,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE (user_id, category, key)
);

-- 2. RECOVERY LOGS
-- Stores daily recovery metrics (sleep, stress, readiness)
CREATE TABLE IF NOT EXISTS public.recovery_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    sleep_hours NUMERIC(4,2),
    stress_level INT CHECK (stress_level >= 1 AND stress_level <= 10),
    soreness_level INT CHECK (soreness_level >= 1 AND soreness_level <= 10),
    energy_level INT CHECK (energy_level >= 1 AND energy_level <= 10),
    readiness_score INT CHECK (readiness_score >= 0 AND readiness_score <= 100),
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    UNIQUE (user_id, date)
);

-- NOTE: nutrition_logs has been temporarily omitted due to a naming collision with the legacy database.
-- It will be migrated via the Strangler Pattern at a later date.

-- 4. USER GOALS
-- Tracks explicit user goals to pass into the AI context
CREATE TABLE IF NOT EXISTS public.user_goals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    goal_type TEXT NOT NULL, -- e.g. 'WEIGHT_LOSS', 'STRENGTH'
    target_value NUMERIC(10,2),
    current_value NUMERIC(10,2),
    target_date DATE,
    status TEXT DEFAULT 'ACTIVE', -- ACTIVE, ACHIEVED, ABANDONED
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- 5. RECOMMENDATIONS
-- Rule-based recommendations generated by the backend
CREATE TABLE IF NOT EXISTS public.recommendations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- e.g. 'WORKOUT', 'RECOVERY', 'NUTRITION'
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- TRIGGERS
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_ai_memory_modtime') THEN
        CREATE TRIGGER update_ai_memory_modtime BEFORE UPDATE ON public.ai_memory FOR EACH ROW EXECUTE FUNCTION update_modified_column();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_recovery_logs_modtime') THEN
        CREATE TRIGGER update_recovery_logs_modtime BEFORE UPDATE ON public.recovery_logs FOR EACH ROW EXECUTE FUNCTION update_modified_column();
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_trigger WHERE tgname = 'update_user_goals_modtime') THEN
        CREATE TRIGGER update_user_goals_modtime BEFORE UPDATE ON public.user_goals FOR EACH ROW EXECUTE FUNCTION update_modified_column();
    END IF;
END$$;

-- ROW LEVEL SECURITY (RLS)
ALTER TABLE public.ai_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recovery_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;

-- Security Policies (Members manage their own data)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members manage own memory' AND tablename = 'ai_memory') THEN
        CREATE POLICY "Members manage own memory" ON public.ai_memory FOR ALL USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members manage own recovery' AND tablename = 'recovery_logs') THEN
        CREATE POLICY "Members manage own recovery" ON public.recovery_logs FOR ALL USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members manage own goals' AND tablename = 'user_goals') THEN
        CREATE POLICY "Members manage own goals" ON public.user_goals FOR ALL USING (auth.uid() = user_id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Members read own recommendations' AND tablename = 'recommendations') THEN
        CREATE POLICY "Members read own recommendations" ON public.recommendations FOR SELECT USING (auth.uid() = user_id);
    END IF;
END$$;
